id: A70BA44BA
title: 'The Swift Fulfilment of Wishes: A Prayer for the Swift Return of the Supreme
  Tulku of the Fifth Drubwang Dzogchen Rinpoche'
type: translation
pechas:
- ID05345F4
- IC5C4CAA1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:52:17.029438
  last_modified_at: 2023-01-04 11:52:17.029467
  collections:
  - Fifth Dzogchen Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  ID05345F4/1EDE: A473
  IC5C4CAA1/B72E: A473
